{
 "title": "\"SMR\" Storage Account Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Total Storage Consumption(in TiB)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(Blob_capacity{subscription=\"sap-hec-0011\",job=\"Blob_monitor\",Customer=\"smr\"})"
    }
   ]
  },
  {
   "title": "Storage Account : sahec53smrdiag0001",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Blob_capacity{storageaccount=~\".*diag.*\",job=\"Blob_monitor\",Customer=\"smr\",subscription=\"sap-hec-0011\"}"
    }
   ]
  },
  {
   "title": "Storage Account : sahec53smrlock0001",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Blob_capacity{storageaccount=~\".*lock.*\",job=\"Blob_monitor\",Customer=\"smr\",subscription=\"sap-hec-0011\"}"
    }
   ]
  },
  {
   "title": "Storage Account : sahec53smrtransfer0001",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Blob_capacity{storageaccount=~\".*transfer.*\",job=\"Blob_monitor\",Customer=\"smr\",subscription=\"sap-hec-0011\"}"
    }
   ]
  },
  {
   "title": "Storage Account : sahec53smrbackup0001",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Blob_capacity{storageaccount=~\".*backup.*\",job=\"Blob_monitor\",Customer=\"smr\",subscription=\"sap-hec-0011\"}"
    }
   ]
  }
 ]
}