{
 "title": "Top 20 Consumers of Each Azure Storage Account",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": " Transfer Storage Account",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(20,(Blob_capacity{storageaccount=~\".*transfer.*\"}))"
    }
   ]
  },
  {
   "title": "Diagnostic Storage Account",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "topk(20,(Blob_capacity{storageaccount=~\".*diag.*\"}))"
    }
   ]
  },
  {
   "title": "Lock Storage Account",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "topk(20,(Blob_capacity{storageaccount=~\".*lock.*\"}))"
    }
   ]
  },
  {
   "title": "Backup Storage Account",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "topk(3,(Blob_capacity{storageaccount=~\".*backup.*\",job=\"Blob_monitor\"}))"
    }
   ]
  }
 ]
}