{
 "title": "Cumulative",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Total Azure Storage Account",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(Blob_capacity{job=\"Blob_monitor\",subscription!~\"sap-hec-0001|sap-hec-0002|sap-hec-0003|sap-hec-0006|sap-hec-0007|sap-hec-0008|sap-hec-0009|sap-hec-0010\"})"
    }
   ]
  },
  {
   "title": "Total Consumed Capacity ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Blob_capacity{job=\"Blob_monitor\",subscription!~\"sap-hec-0001|sap-hec-0002|sap-hec-0003|sap-hec-0006|sap-hec-0007|sap-hec-0008|sap-hec-0009|sap-hec-0010\"})"
    }
   ]
  },
  {
   "title": "Count of Azure Storage Account by type",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(Blob_capacity{storageaccount=~\".*transfer.*\",subscription!~\"sap-hec-0001|sap-hec-0002|sap-hec-0003|sap-hec-0006|sap-hec-0007|sap-hec-0008|sap-hec-0009|sap-hec-0010\"})"
    },
    {
     "expr": "count(Blob_capacity{storageaccount=~\".*diag.*\",subscription!~\"sap-hec-0001|sap-hec-0002|sap-hec-0003|sap-hec-0006|sap-hec-0007|sap-hec-0008|sap-hec-0009|sap-hec-0010\"})"
    },
    {
     "expr": "count(Blob_capacity{storageaccount=~\".*lock.*\",subscription!~\"sap-hec-0001|sap-hec-0002|sap-hec-0003|sap-hec-0006|sap-hec-0007|sap-hec-0008|sap-hec-0009|sap-hec-0010\"})"
    },
    {
     "expr": "count(Blob_capacity{storageaccount=~\".*backup.*\",subscription!~\"sap-hec-0001|sap-hec-0002|sap-hec-0003|sap-hec-0006|sap-hec-0007|sap-hec-0008|sap-hec-0009|sap-hec-0010\"})"
    },
    {
     "expr": "count(Blob_capacity{storageaccount!~\".*backup.*|.*transfer.*|.*lock.*|.*diag.*\",subscription!~\"sap-hec-0001|sap-hec-0002|sap-hec-0003|sap-hec-0006|sap-hec-0007|sap-hec-0008|sap-hec-0009|sap-hec-0010\"})"
    }
   ]
  },
  {
   "title": "Azure Storage Account Consumption Breakup (in TB)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Blob_capacity{storageaccount=~\".*transfer.*\",subscription!~\"sap-hec-0001|sap-hec-0002|sap-hec-0003|sap-hec-0006|sap-hec-0007|sap-hec-0008|sap-hec-0009|sap-hec-0010\"})",
     "legendFormat": "Transfer Storage Account"
    },
    {
     "expr": "sum(Blob_capacity{storageaccount=~\".*diag.*\",subscription!~\"sap-hec-0001|sap-hec-0002|sap-hec-0003|sap-hec-0006|sap-hec-0007|sap-hec-0008|sap-hec-0009|sap-hec-0010\"})",
     "legendFormat": "Diagnostics Storage Account"
    },
    {
     "expr": "sum(Blob_capacity{storageaccount=~\".*lock.*\",subscription!~\"sap-hec-0001|sap-hec-0002|sap-hec-0003|sap-hec-0006|sap-hec-0007|sap-hec-0008|sap-hec-0009|sap-hec-0010\"})",
     "legendFormat": "Lock Storage Account"
    },
    {
     "expr": "sum(Blob_capacity{storageaccount=~\".*backup.*\",subscription!~\"sap-hec-0001|sap-hec-0002|sap-hec-0003|sap-hec-0006|sap-hec-0007|sap-hec-0008|sap-hec-0009|sap-hec-0010\"})",
     "legendFormat": "Backup Storage Account"
    },
    {
     "expr": "sum(Blob_capacity{storageaccount!~\".*backup.*|.*transfer.*|.*lock.*|.*diag.*\",subscription!~\"sap-hec-0001|sap-hec-0002|sap-hec-0003|sap-hec-0006|sap-hec-0007|sap-hec-0008|sap-hec-0009|sap-hec-0010\"})",
     "legendFormat": "Other Storage Account"
    }
   ]
  }
 ]
}